//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Usuarios
    {
        [Display(Name = "#")]
        public int ID { get; set; }
		[Display(Name = "Nombre del usuario")]
		public string Nombre { get; set; }
		[Display(Name = "Correo del usuario")]
		public string Correo { get; set; }
		[Display(Name = "Telefono del usaurio")]
		public string Telefono { get; set; }
    }
}
